### ISSUE TITLE
Build error while installing.

### ISSUE THREAD

**Issue by gk1** [websockets/utf-8-validate#18]
[root@wsgateway nodetest]# npm i utf-8-validate
npm http GET https://registry.npmjs.org/utf-8-validate
npm http 304 https://registry.npmjs.org/utf-8-validate
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings

> utf-8-validate@1.2.1 install /var/www/html/nodetest/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/var/www/html/nodetest/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../../nan/nan.h:316: error: âREPLACE_INVALID_UTF8â is not a member of âv8::Stringâ
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory`/var/www/html/nodetest/node_modules/utf-8-validate/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/nodetest/node_modules/utf-8-validate
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by nicofff** [comment]
It looks like the error is dependent on the node version.

I was getting a similar error on nodejs v4.0 (latest version on arch linux repos), trying to install socket.io-client. The issue seems to be resolved for node v4.0 on the latest release of this repo (which is not used by the last release of socket.io-client).

Now I'm trying to install on an Amazon linux with node v0.10.36, and I'm getting the same error as @gk1

Seems like v1.1.0 is the last version compatible with node v0.10.36

**Comment by lpinca** [comment]
Closing this as Node.js 0.10 is no longer supported.
